apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: aws-secret-fetcher
      init:
        command: ["/bin/sh", "-c"]
        args: ["echo 'Fetching secrets from AWS Secrets Manager'"]
      generate:
        command: ["/bin/sh", "-c"]
        args: [
          "DB_USERNAME=$(aws secretsmanager get-secret-value --secret-id db-username --query SecretString --output text)",
          "DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id db-password --query SecretString --output text)",
          "API_KEY=$(aws secretsmanager get-secret-value --secret-id api-key --query SecretString --output text)",
          "sed -e 's/{{db_username}}/'\"$DB_USERNAME\"'/g' -e 's/{{db_password}}/'\"$DB_PASSWORD\"'/g' -e 's/{{api_key}}/'\"$API_KEY\"'/g' ./manifests/deployment.yaml"
        ]
