apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: fir3eye/springboot1:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          value: "{{db_username}}"  # Placeholder for the secret from AWS
        - name: DB_PASSWORD
          value: "{{db_password}}"  # Placeholder for the secret from AWS
        - name: API_KEY
          value: "{{api_key}}"       # Placeholder for the secret from AWS
