apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sourav3227/Argo-manifest.git'  # Replace with your repo URL
    path: manifest
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  plugin:
    name: aws-secret-fetcher  # Custom plugin to fetch secrets from AWS Secrets Manager

