apiVersion: secret-replacer.argoproj-labs.io/v1alpha1
kind: SecretReplacer
metadata:
  name: my-secret-replacer
  namespace: argocd
spec:
  secrets:
    - name: my-secret
      stringData:
        AWS_ACCESS_KEY_ID: <path:secret/data/aws_access_key_id>
        AWS_SECRET_ACCESS_KEY: <path:secret/data/aws_secret_access_key>